version: '2'
services:
  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/opt/home-js
    depends_on:
      - db
  db:
    image: "mongo:latest"
  broker:
    image: "ansi/mosquitto"
    ports:
      - "1883:1883"
