version: '2'
services:
  web:
    build: .
    ports:
      - '3030:3030'
    volumes:
      - .:/opt/home-js
      - /opt/home-js/node_modules
    depends_on:
      - db
  db:
    image: 'mongo:latest'
    ports:
      - '27018:27017'
  broker:
    image: 'ansi/mosquitto'
    ports:
      - '1883:1883'
  mock-device:
    build: mock-device
    depends_on:
      - broker
