version: '3'
networks:
  main:
    driver: overlay
services:
  web:
    build: .
    # image: 'handsofblue67/homejs'
    ports:
      - '3030:3030'
      - '5858:5858'
    volumes:
      - .:/opt/home-js
      - /opt/home-js/node_modules
    depends_on:
      - db
    networks:
      - main
  db:
    image: 'mongo:latest'
    ports:
      - '27017:27017'
    networks:
      - main
    deploy:
      placement:
        constraints: [node.role == manager]
  broker:
    image: 'ansi/mosquitto'
    ports:
      - '1883:1883'
    networks:
      - main 
  mock-device:
    build: mock-device
    # image: 'handsofblue67/mockdevice' 
    depends_on:
      - broker
    networks:
      - main 
