version: '2'
services:
  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/home/app/home-js
      - /home/app/home-js/node_modules
    depends_on:
      - db
      - broker
  db:
    image: "mongo:latest"
  broker:
    image: "ansi/mosquitto"
    ports:
      - "1883:1883"
