version: '3.2'
networks:
  main:
    driver: overlay
services:
  web:
    build: .
    # image: 'homejs_web'
    ports:
      - '3030:3030'
      - '5858:5858'
    volumes:
      - .:/home/node/home-js
      - /home/node/home-js/node_modules
    depends_on:
      - db
    networks:
      - main
  db:
    image: 'mongo:latest'
    ports:
      - '27017:27017'
    networks:
      - main
    volumes:
      - ./data/mongo:/data/db
    deploy:
      placement:
        constraints: [node.role == manager]
  broker:
    image: 'ansi/mosquitto'
    ports:
      - '1883:1883'
    networks:
      - main 
  mock-device:
    # build: mock-device
    image: 'handsofblue67/mockdevice' 
    depends_on:
      - broker
    networks:
      - main 
